### ISSUE TITLE
Use schema references, not Python references

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb-io#11]
Reused object definitions in I/O schema are linked on Python level. This makes the resulting schema JSON harder to read, as the reused definitions are simply copied there. Instead, define and reuse them on the schema level.

E.g. the [v4 schema](https://github.com/kernelci/kcidb-io/blob/main/kcidb_io/schema/v4.py) stores schema for each separate object type in Python variables `JSON_CHECKOUT`, `JSON_BUILD`, and `JSON_TEST`, and then references them when defining the complete schema in `JSON`. Similarly, `JSON_RESOURCE` is referenced in multiple places.

Instead, we should define and (re)use them within the schema itself, as described in [8.2.4. Schema Re-Use With "$defs"](https://json-schema.org/draft/2020-12/json-schema-core.html#defs) of the JSON Schema specification. We can still use the Python variables for storing the pieces, if needed, but linking and reusing should be done in the schema itself.

When changing this, take note of how `kcidb.orm` references the particular object type schemas and make sure they keep working after the change.

**Comment by mrbazzan** [comment]
CC: @spbnick

**Comment by mrbazzan** [comment]
CC: @spbnick
