### ISSUE TITLE
Remove all functions from kcidb_io.schema

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb-io#44]
Since all functions in `kcidb_io.schema` are using the corresponding methods of the latest schema's object now, remove them to reduce confusion.

Consider first adding [warnings](https://docs.python.org/3/library/warnings.html) when any of the functions is used and adding a deprecation note into the following release. Remove the functions in the release after.

**Comment by spbnick** [comment]
Warnings have been there for a while, and now we can remove all the deprecated functions (calling `_warn_deprecated`) from [`kcidb_io.schema`](https://github.com/kernelci/kcidb-io/blob/main/kcidb_io/schema/__init__.py) module, as well as the `_warn_deprecated` function itself.

**Comment by NikkyXO** [comment]
@spbnick i will like to work on this. Can I have this assigned to me

**Comment by spbnick** [comment]
Absolutely! Have fun!
