### ISSUE TITLE
Move all functions from kcidb_io module into schema version class

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb-io#45]
Since KCIDB is [stopping](https://github.com/kernelci/kcidb/issues/155) using the latest version of the I/O schema, the functions in the `kcidb_io` module which refer to the latest version of the schema become useless, and their presence confusing and dangerous. Instead, move all of them into methods of the schema version class.

Consider first copying the functions to the class, then adding warnings when any of the old functions is used, and adding a deprecation note into the following release. Remove the functions in the release after.

**Comment by spbnick** [comment]
The functions are moved, and the warnings were there for a while now, so we can remove all deprecated functions from the [`kcidb_io` module](https://github.com/kernelci/kcidb-io/blob/main/kcidb_io/__init__.py) (those calling `_warn_deprecated`), as well as the `_warn_deprecated` function itself.

**Comment by khanjasir90** [comment]
@spbnick I am an outreachy applicant, can I work on this issue

**Comment by spbnick** [comment]
Hi Mohd, of course! Welcome to the project! Assigned to you. Would be glad to see you on our Slack as well. If you'd like to join, send me an email to spbnick@gmail.com, and I'll send an invite to your address.

**Comment by spbnick** [comment]
Sorry, Mohd, another applicant resolved this issue by mistake, and I didn't notice that :see_no_evil: Please pick another issues, if you would still like to contribute. Closing this one.
