### ISSUE TITLE
Rename schema test files to match modules

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb-io#69]
When we were renaming schema version files to match the `vXX_XX.py` pattern, we forgot to rename their test files along with them. Rename the `test_v*.py` files in the `kcidb_io/schema` directory to match the names of modules they're testing.

**Comment by Aman-Jamshed** [comment]
Hey @spbnick I'm an Outreachy applicant. Can I work on this issue?

**Comment by Aman-Jamshed** [comment]
Thankyou! @spbnick 
Please email me the link to join the Slack channel as well at amanjamshed3@gmail.com
